[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
linker = "ld"
rustflags = [
  "-C", "link-arg=-Tsrc/linker.ld",
  "-C", "link-arg=entry/entry.o",
  "-C", "relocation-model=static",
]
