[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
linker = "ld"
rustflags = [
  "-C", "link-arg=-Tsrc/linker.ld",
  "-C", "link-arg=asm/build/entry.o",
  "-C", "link-arg=asm/build/vectors.o",
  "-C", "link-arg=asm/build/syscall.o",
  "-C", "relocation-model=static",
]
